# A small but complete SAP: one codelist, one outcome cohort built from typed
# operations, one denominator, one restricted analysis, one unmappable analysis.
testSap <- function() {
  list(
    sap_schema_version = "0.4.30",
    study = list(
      title = "Asthma prevalence study",
      study_code = "TEST-001",
      authors = list("Dr. Smith", "Dr. Jones"),
      version = "1.0",
      min_cell_count = 5,
      background = "Background of the asthma study.",
      aim = "What is the prevalence of asthma?",
      objectives = list(
        list(id = "obj_1", text = "To estimate the prevalence of asthma")
      )
    ),
    cdm_sources = list(
      list(name = "Database A", source_key = "DB_A", country = "UK"),
      list(name = "Database B", source_key = "DB_B", country = "Spain")
    ),
    codelists = list(
      list(name = "cs_asthma", category = "Index event", description = NULL),
      list(name = "cs_unused", category = "Other", description = NULL)
    ),
    cohorts = list(
      list(
        name = "Asthma",
        kind = "outcome",
        operations = list(
          list(op = "concept_cohort", codelist = "cs_asthma"),
          list(op = "require_first_entry"),
          list(op = "pad_cohort_end", days = 365)
        )
      ),
      list(
        name = "General population",
        kind = "denominator",
        cohortDateRange = list("2015-01-01", NULL),
        ageGroup = list(list(0, 150), list(0, 17), list(18, 150)),
        sex = list("Both"),
        daysPriorObservation = list(365),
        requirementInteractions = TRUE
      )
    ),
    proposed_analyses = list(
      list(
        name = "Asthma period prevalence",
        analysis_type = "estimatePeriodPrevalence",
        role = "primary",
        objectives = list("obj_1"),
        data_sources = list("DB_A"),
        parameters = list(
          denominatorTable = "General population",
          outcomeTable = "Asthma",
          interval = "years",
          completeDatabaseIntervals = TRUE,
          fullContribution = FALSE,
          level = "person"
        )
      ),
      list(
        name = "Something else entirely",
        analysis_type = "Other",
        parameters = list()
      )
    )
  )
}

test_that("generateStudyCode fills the studyCode analysis files from a SAP", {
  temp_dir <- here::here(tempdir(), omopgenerics::uniqueTableName())
  initStudy(directory = temp_dir, diagnostics = FALSE)
  study_code <- file.path(temp_dir, "studyCode")

  expect_no_error(generateStudyCode(testSap(), study_code))

  # codelistCreation.R: only the cited codelist, read from its by-category path
  codelists <- paste(
    readLines(file.path(study_code, "codelist", "codelistCreation.R")),
    collapse = "\n"
  )
  expect_true(grepl("Generated by OmopStudyBuilder", codelists))
  expect_true(grepl(
    'cs_asthma <- importCodelist\\(path = here\\("codelist/Index_event/cs_asthma.csv"\\), type = "csv"\\)',
    codelists
  ))
  expect_false(grepl("cs_unused", codelists))
  # the folder the CSV is expected in is created
  expect_true(dir.exists(file.path(study_code, "codelist", "Index_event")))

  # instantiateCohorts.R: the typed cohort as a CohortConstructor pipeline
  cohorts <- paste(
    readLines(file.path(study_code, "cohorts", "instantiateCohorts.R")),
    collapse = "\n"
  )
  expect_true(grepl("cdm\\$asthma <- conceptCohort\\(", cohorts))
  expect_true(grepl("requireIsFirstEntry\\(\\)", cohorts))
  expect_true(grepl("padCohortEnd\\(days = 365\\)", cohorts))
  expect_true(grepl("addCohortTableIndex\\(\\)", cohorts))
  # the denominator is generated in the analyses file, not here
  expect_false(grepl("generateDenominatorCohortSet", cohorts))

  # incidencePrevalence.R: denominator set, estimate, guard, and SAP labels
  analyses <- paste(
    readLines(file.path(study_code, "analyses", "incidencePrevalence.R")),
    collapse = "\n"
  )
  expect_true(grepl("cdm <- generateDenominatorCohortSet\\(", analyses))
  expect_true(grepl('"general_population"', analyses))
  expect_true(grepl("estimatePeriodPrevalence\\(", analyses))
  expect_true(grepl('results\\[\\["asthma_period_prevalence_1"\\]\\]', analyses))
  # the analysis is restricted to DB_A, so it is guarded and the excluded branch
  # still defines the variable
  expect_true(grepl('omopgenerics::cdmName\\(cdm\\) %in% c\\("DB_A"\\)', analyses))
  expect_true(grepl("emptySummarisedResult\\(\\)", analyses))
  # role and objectives reach both the comment and the sapTag call
  expect_true(grepl("\\(primary\\)", analyses))
  expect_true(grepl('role = "primary"', analyses))
  expect_true(grepl("sapTag", analyses))
  # the unmappable analysis is listed rather than silently dropped
  expect_true(grepl("Something else entirely", analyses))
  expect_true(grepl("No IncidencePrevalence function maps onto analysis type", analyses))

  # codeToRun.R and runStudy.R are never touched
  expect_true(grepl("library\\(DBI\\)",
                    paste(readLines(file.path(study_code, "codeToRun.R")), collapse = "\n")))
})

test_that("generateStudyCode accepts a path to a SAP JSON file", {
  temp_dir <- here::here(tempdir(), omopgenerics::uniqueTableName())
  initStudy(directory = temp_dir, diagnostics = FALSE)
  study_code <- file.path(temp_dir, "studyCode")

  sap_path <- tempfile(fileext = ".json")
  writeLines(
    jsonlite::toJSON(testSap(), auto_unbox = TRUE, na = "null", null = "null"),
    sap_path
  )
  expect_no_error(generateStudyCode(sap_path, study_code))
  analyses <- paste(
    readLines(file.path(study_code, "analyses", "incidencePrevalence.R")),
    collapse = "\n"
  )
  expect_true(grepl("estimatePeriodPrevalence\\(", analyses))

  # errors: missing file, missing directory, wrong type
  expect_error(generateStudyCode(tempfile(fileext = ".json"), study_code))
  expect_error(generateStudyCode(testSap(), tempfile()))
  expect_error(generateStudyCode(1L, study_code))
})

test_that("generateStudyCode accepts a jsonl file, using its last record", {
  temp_dir <- here::here(tempdir(), omopgenerics::uniqueTableName())
  initStudy(directory = temp_dir, diagnostics = FALSE)
  study_code <- file.path(temp_dir, "studyCode")

  one_line <- function(sap) {
    jsonlite::toJSON(sap, auto_unbox = TRUE, na = "null", null = "null")
  }

  # two records: an older version and the current one -- the last must win
  old_sap <- testSap()
  old_sap$study$title <- "Old title"
  old_sap$study$version <- "0.9"
  sap_path <- tempfile(fileext = ".jsonl")
  writeLines(c(one_line(old_sap), one_line(testSap())), sap_path)

  expect_message(
    generateStudyCode(sap_path, study_code),
    "2 records"
  )
  analyses <- paste(
    readLines(file.path(study_code, "analyses", "incidencePrevalence.R")),
    collapse = "\n"
  )
  expect_true(grepl("Version: 1.0", analyses, fixed = TRUE))
  expect_false(grepl("Version: 0.9", analyses, fixed = TRUE))

  # a single-record jsonl works without the multi-record message
  single_path <- tempfile(fileext = ".jsonl")
  writeLines(one_line(testSap()), single_path)
  expect_no_error(generateStudyCode(single_path, study_code))

  # an empty jsonl is an error, not a silently empty study
  empty_path <- tempfile(fileext = ".jsonl")
  writeLines(character(0), empty_path)
  expect_error(generateStudyCode(empty_path, study_code), "no records")

  skip()
  # initStudy takes a jsonl too
  temp_dir2 <- here::here(tempdir(), omopgenerics::uniqueTableName())
  expect_no_error(initStudy(directory = temp_dir2, diagnostics = FALSE, sap = sap_path))
  readme <- paste(readLines(file.path(temp_dir2, "README.md")), collapse = "\n")
  expect_true(grepl("Asthma prevalence study", readme))
  expect_false(grepl("Old title", readme))
})

test_that("initStudy with a sap generates study code and fills metadata", {
  skip()

  temp_dir <- here::here(tempdir(), omopgenerics::uniqueTableName())
  expect_no_error(initStudy(directory = temp_dir, sap = testSap()))

  # README metadata comes from the SAP
  readme <- paste(readLines(file.path(temp_dir, "README.md")), collapse = "\n")
  expect_true(grepl("Asthma prevalence study", readme))
  expect_true(grepl("Dr. Smith, Dr. Jones", readme))
  expect_true(grepl("Background of the asthma study.", readme))

  # the studyCode analysis files are generated
  analyses <- paste(
    readLines(file.path(temp_dir, "studyCode", "analyses", "incidencePrevalence.R")),
    collapse = "\n"
  )
  expect_true(grepl("estimatePeriodPrevalence\\(", analyses))

  # explicit arguments still win over the SAP
  temp_dir2 <- here::here(tempdir(), omopgenerics::uniqueTableName())
  initStudy(directory = temp_dir2, sap = testSap(), studyTitle = "My own title")
  readme2 <- paste(readLines(file.path(temp_dir2, "README.md")), collapse = "\n")
  expect_true(grepl("My own title", readme2))
  expect_false(grepl("Asthma prevalence study", readme2))
})

test_that("initStudy without a sap keeps the current behaviour", {
  temp_dir <- here::here(tempdir(), omopgenerics::uniqueTableName())
  initStudy(directory = temp_dir, diagnostics = FALSE)
  # the SAP-owned files exist and are empty, exactly as the template ships them
  analyses <- readLines(
    file.path(temp_dir, "studyCode", "analyses", "incidencePrevalence.R")
  )
  expect_false(any(nzchar(analyses)))
})

test_that("initStudy errors when a sap is given without the study folders", {
  skip()
  temp_dir <- here::here(tempdir(), omopgenerics::uniqueTableName())
  expect_error(
    initStudy(directory = temp_dir, study = FALSE, sap = testSap()),
    "study = TRUE"
  )
})
